// Generated by CoffeeScript 1.6.3
app.controller('addUserCtrl', [
  '$scope', function(scope) {
    var animation, client;
    console.log("add user ctrl");
    animation = false;
    scope.masters = ["Ким Диана", "Дмитрий Ногиев"];
    client = function() {
      return {
        savings: 0,
        discount: 0,
        phone: [
          {
            type: "мобильный",
            number: ""
          }, {
            type: "домашний",
            number: ""
          }
        ],
        masters: []
      };
    };
    scope.client = new client;
    scope.saveClient = function() {
      console.log("Saving user:");
      scope.client.reg_date = new Date();
      return console.log(scope.client);
    };
    scope.setPhone = function(index) {
      if (index === 0) {
        return scope.client.phone[index].number = scope.mobilephone;
      } else {
        return scope.client.phone[index].number = scope.homephone;
      }
    };
    scope.setBirthday = function() {
      return scope.client.birthday = new Date(scope.birthday);
    };
    scope.setMaster = function() {
      return scope.client.master = scope.clientmaster;
    };
    scope.cleanFields = function() {
      scope.client = new client;
      scope.mobilephone = "";
      scope.homephone = "";
      return console.log(scope.client);
    };
    scope.addMaster = function(master) {
      if (master !== void 0 && master.length > 0) {
        scope.client.masters.push(master);
      }
      return console.log(scope.client.masters);
    };
    scope.removeMaster = function(master) {
      return scope.client.masters.splice(scope.client.masters.indexOf(master), 1);
    };
  }
]);
