// Generated by CoffeeScript 1.6.3
app.controller('addUserCtrl', [
  '$scope', function(scope) {
    var animation;
    console.log("add user ctrl");
    animation = false;
    scope.masters = ["Ким Диана", "Дмитрий Ногиев"];
    scope.client = {
      savings: 0,
      discount: 0,
      phone: [
        {
          type: "мобильный",
          number: ""
        }, {
          type: "домашний",
          number: ""
        }
      ]
    };
    scope.saveClient = function() {
      console.log("Saving user:");
      scope.client.reg_date = new Date();
      return console.log(scope.client);
    };
    scope.setPhone = function(index) {
      if (index === 0) {
        return scope.client.phone[index].number = scope.mobilephone;
      } else {
        return scope.client.phone[index].number = scope.homephone;
      }
    };
    scope.setBirthday = function() {
      return scope.client.birthday = new Date(scope.birthday);
    };
    return scope.setMaster = function() {
      return scope.client.master = scope.clientmaster;
    };
  }
]);
