// Generated by CoffeeScript 1.6.3
app.controller('notesCtrl', [
  '$scope', function(scope) {
    return console.log("notes ctrl");
  }
]);

app.controller('addNoteCtrl', [
  '$scope', function(scope) {
    return console.log("add note ctrl");
  }
]);
