// Generated by CoffeeScript 1.6.3
app.config([
  '$routeProvider', function(routeProvider) {
    routeProvider.when('/', {
      controller: 'notesCtrl',
      templateUrl: 'views/notes.html'
    });
    return routeProvider.when('/addclient', {
      controller: 'addUserCtrl',
      templateUrl: 'views/newclient.html'
    });
  }
]);
