// Generated by CoffeeScript 1.6.3
app.factory('clientsService', [
  '$http', function(http) {
    return {
      create: function(client) {
        var result;
        console.log("create called");
        return result = http.post('/api/clients/create', client);
      }
    };
  }
]);
